import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BadgePercent,
  Banknote,
  BarChart3,
  BookOpen,
  Bot,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  ChartSpline,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CodeXml,
  Compass,
  Contact,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileCheck,
  FileClock,
  FileSignature,
  FileText,
  Filter,
  FolderCheck,
  Fuel,
  Gauge,
  Globe,
  GraduationCap,
  GripVertical,
  Handshake,
  HardHat,
  Headset,
  HeartPulse,
  Image,
  Info,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Library,
  LifeBuoy,
  Linkedin,
  List,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  Newspaper,
  Package,
  PenLine,
  Pencil,
  Phone,
  Play,
  Plus,
  Presentation,
  Radio,
  ReceiptText,
  RefreshCw,
  Route,
  Rows3,
  Save,
  Scale,
  Search,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Split,
  Star,
  Sun,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Twitter,
  Type,
  Upload,
  UserPlus,
  Users,
  Wrench,
  X,
} from "lucide-react";

/**
 * Explicit icon registry so the bundle only carries the icons the site uses. Names are the Lucide
 * kebab-case names the prototype used (data-lucide="chart-spline"). Add new icons here.
 */
const ICONS = {
  "activity": Activity,
  "alert-circle": AlertCircle,
  "arrow-right": ArrowRight,
  "award": Award,
  "badge-check": BadgeCheck,
  "badge-percent": BadgePercent,
  "banknote": Banknote,
  "bar-chart-3": BarChart3,
  "book-open": BookOpen,
  "bot": Bot,
  "briefcase": Briefcase,
  "building": Building,
  "building-2": Building2,
  "calculator": Calculator,
  "calendar-days": CalendarDays,
  "chart-spline": ChartSpline,
  "check": Check,
  "check-circle-2": CheckCircle2,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cloud": Cloud,
  "code-xml": CodeXml,
  "compass": Compass,
  "contact": Contact,
  "database": Database,
  "factory": Factory,
  "file-check": FileCheck,
  "file-clock": FileClock,
  "file-signature": FileSignature,
  "file-text": FileText,
  "folder-check": FolderCheck,
  "fuel": Fuel,
  "gauge": Gauge,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "handshake": Handshake,
  "hard-hat": HardHat,
  "headset": Headset,
  "heart-pulse": HeartPulse,
  "landmark": Landmark,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "library": Library,
  "life-buoy": LifeBuoy,
  "lock": Lock,
  "map": Map,
  "megaphone": Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "newspaper": Newspaper,
  "package": Package,
  "pen-line": PenLine,
  "phone": Phone,
  "presentation": Presentation,
  "radio": Radio,
  "receipt-text": ReceiptText,
  "route": Route,
  "rows-3": Rows3,
  "scale": Scale,
  "server": Server,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "sparkles": Sparkles,
  "split": Split,
  "target": Target,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "truck": Truck,
  "type": Type,
  "user-plus": UserPlus,
  "users": Users,
  "wrench": Wrench,
  "x": X,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "arrow-left": ArrowLeft,
  "arrow-up-right": ArrowUpRight,
  "plus": Plus,
  "minus": Minus,
  "trash-2": Trash2,
  "eye": Eye,
  "eye-off": EyeOff,
  "pencil": Pencil,
  "save": Save,
  "upload": Upload,
  "download": Download,
  "search": Search,
  "log-out": LogOut,
  "external-link": ExternalLink,
  "mail": Mail,
  "map-pin": MapPin,
  "menu": Menu,
  "moon": Moon,
  "sun": Sun,
  "play": Play,
  "circle-play": CirclePlay,
  "filter": Filter,
  "copy": Copy,
  "settings": Settings,
  "image": Image,
  "list": List,
  "calendar": Calendar,
  "star": Star,
  "linkedin": Linkedin,
  "twitter": Twitter,
  "circle-check": CircleCheck,
  "circle-alert": CircleAlert,
  "info": Info,
  "refresh-cw": RefreshCw,
  "more-horizontal": MoreHorizontal,
  "grip-vertical": GripVertical,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type IconProps = Omit<LucideProps, "ref"> & { name: IconName; size?: number };

/**
 * Lucide icon at the prototype's default 22px / 2px stroke. The data-lucide attribute is kept because
 * styles/site.css recolours specific strokes of the service icon set orange by that attribute.
 */
export function Icon({ name, size = 22, ...rest }: IconProps) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp data-lucide={name} width={size} height={size} aria-hidden="true" {...rest} />;
}

export function isIconName(name: string): name is IconName {
  return name in ICONS;
}
